version: '3.8'

services:
  frontend:
    build: ./docker/frontend
    ports:
      - "4173:4173"
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}

  backend:
    build: ./docker/backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=${MONGO_URI}

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
