services:
  - type: web
    name: astrobalendar-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: MONGODB_URI
        fromDatabase: MONGODB_URI
      - key: JWT_SECRET_KEY
        fromDatabase: JWT_SECRET_KEY
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: "7"
      - key: DEBUG
        value: "False"
      - key: CORS_ORIGINS
        value: "https://yourfrontenddomain.com"
